#!/bin/sh

#### Bootstrap

# This snippet is
if [ -n "$-" -a -z "${-##*a*}" ]; then
    # sourced by simple-cdd build environment

    # This is default path for build-simple-cdd(1) set by internal VARIABLES
    # in python3/dist-packages/simple_cdd/variables.py.
    simple_cdd_dir="${simple_cdd_dir:-$PWD}"

    # Usage: include_deps <group> <profile> [<profile_desc>] ...
    include_deps()
    {
        # Order is important to set @profiles and @auto_profiles correctly
        include_skip_profile_all "${path:+$path/../}./$2.conf"

        # Make sure we agreed on profile name
        if [ "$2" != "$profile" ]; then
            echo >&2 "$1: build script ($2) and config ($profile) profile name mismatch"
            exit 1
        fi

        # Instance specific temporary directory
        export simple_cdd_temp="${simple_cdd_dir}/tmp/$2"
    }

    if [ -z "${1:+x}" ]; then
        echo >&2 'usage: . ./profiles/sh/common <group> <profile> [<profile_desc>]'
        exit 1
    fi

    # Execute bootstrap code from distro specific config file
    . "$simple_cdd_dir/profiles/groups/distro.conf" "$@"
else
    # sourced by profile build script

    # Make sure to update adjacent code in profile_env() from
    # distro specific config (e.g. distro.conf) when modifying
    # list of included variables here.
    exec env -i \
        ${PATH+PATH="$PATH"} \
        ${TERM+TERM="$TERM"} \
        ${LOGNAME+LOGNAME="$LOGNAME"} \
        ${USER+USER="$USER"} \
        ${USERNAME+USERNAME="$USERNAME"} \
        ${HOSTNAME+HOSTNAME="$HOSTNAME"} \
        ${HOME+HOME="$HOME"} \
        ${SHELL+SHELL="$SHELL"} \
        ${PWD+PWD="$PWD"} \
        ${MAIL+MAIL="$MAIL"} \
        ${LANG+LANG="$LANG"} \
        ${LANGUAGE+LANGUAGE="$LANGUAGE"} \
        ${LC_ALL+LC_ALL="$LC_ALL"} \
        ${LC_CTYPE+LC_CTYPE="$LC_CTYPE"} \
        build-simple-cdd "$@" --conf "./profiles/$this" ||
    exit
fi

#### Profile configuration
